### ISSUE TITLE
Any instructions to use the code?

### ISSUE THREAD

**Issue by gosha20777** [PnthrLeo/diffusion-augmentation#1]
If there is any instructions to use the code will be provided?

I am developing an open source and non-committal project called [lacmus](https://lacmus.tech), and due to this I am extremely interested in this code to apply it for my application)

Thanks!

P.s. Hi from VISAPP24:-)

**Comment by PnthrLeo** [comment]
Thank you for your interest in our project!

Yes, we are dedicated to provide instructions today🧑‍💻

**Comment by PnthrLeo** [comment]
Usage instructions to the code have been posted!

Unfortunately, the current code is mainly written for the paper results verification. Therefore, the code is not ready to run on any datasets, except the ones presented in the paper.  

However, we are planning to develop improved version of the framework for a common use in the form of Python library soon :-)

**Comment by gosha20777** [comment]
Amazing :heart_eyes:
